import { Alfa_Slab_One } from "next/font/google";
import "./globals.css";

const alfa = Alfa_Slab_One({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "DS-Twoja asystentka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alfa.className}>{children}</body>
    </html>
  );
}
